### PR TITLE
[Client] Add https support

### PR DESCRIPTION
**Pull request by n1t0**

### CODE REVIEW

**Comment by feross** [comment]
Looks good! I'll merge when/if the travis build passes.

**Comment by n1t0** [comment]
Awesome, thanks!

**Comment by feross** [comment]
Published as 2.11.0.

**Comment by feross** [comment]
And just published 2.12.0 to support http trackers that respond with redirects and/or gzip/deflate.

**Comment by n1t0** [comment]
I saw that, you didn't loose a minute!

**Pull request merged**
