### PR TITLE
Added optional cb for createSwarm and getSwarm. Fixes #95

### LINKED ISSUE #95: Pluggable DB interface
I think the code should be more asynchronous when it comes to the methods getSwarm and createSwam. They should take a callback so you can query a DB for peers. Having a million+ torrents in memory just wont work. An upside is persistency.

Any thought on this?

If not Im going to have to fork and refactor the code for my use.

### PR DESCRIPTION
**Pull request by RaulTsc**

### CODE REVIEW

**Comment by feross** [comment]
Unforunately, it's not enough to just support a callback parameter. All the parts of the code that call `getSwarm` need to be reworked to pass a callback.

**Comment by RaulTsc** [comment]
Updated. Please give feedback if not ok as to how I should proceed

**Comment by feross** [comment]
This is close to being right, but it's still a bit off. Thanks for sending the PR nonetheless. I can finish this feature up and do a release.

**Comment by FLYBYME** [comment]
`getSwarm` need to pass back an error for one. Like `getSwarm(function(err,swarm){})`

I think we need to take it a step further then this. Maybe like passing a store object into `new Server` and default back to a basic in memory torrent store. Having getSwarm and getPeers as methods on the store object. This way we dont have to hack the Server.prototype.getSwarm to override the defaults.

**Comment by feross** [comment]
Released as 7.0.0.

**Comment by feross** [comment]
Yeah, getSwarm supports an error callback. I don't think we need a store object. Overriding `createSwarm` and `getSwarm` should work just fine, unless there's some use case you have in mind.

**Pull request closed without merging**
