### PR TITLE
very much wrong email

### PR DESCRIPTION
**Pull request by GusCaplan**

### CODE REVIEW

**Comment by yciabaud** [comment]
This file is generated so I guess this will be overwritten with the next release.

**Comment by DiegoRBaquero** [comment]
@yciabaud https://github.com/feross/bittorrent-tracker/pull/217 should do

**Comment by GusCaplan** [comment]
@yciabaud do you know where it pulls that email from, i will change wherever it gets it from

**Comment by DiegoRBaquero** [comment]
@GusCaplan from the commit. It should be fixed with #217 as it ignores it.

**Pull request merged**
